baseURL: "https://www.aladdinding.com/"
title: 阿拉丁的博客
paginate: 5
theme: PaperMod
defaultContentLanguage: zh

hasCJKLanguage: true
summaryLength: 140
disablePathToLower: true

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

permalinks:
  posts: /:year/:month/:filename/

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Aladdin
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperMod]
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2006-01-01"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
        disableHLJS: true # to disable highlight.js
        disableFingerprinting: true
        favicon: http://img.aladdinding.cn/favicon.ico
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"


    # home-info mode
    homeInfoParams:
        Title: "Welcome to Aladdin's blog Ⓓ"
        Content: >

            - **Be well-grounded and speak up moderately !**


            - **博学而约取，厚积而薄发**。



    socialIcons:
        - name: github
          url: "https://github.com/aladdinding"
        - name: telegram
          url: "https://telegram.me/aladdinding"
        - name: email
          url: "mailto:aladdinding@qq.com"




    analytics:
        google:
            SiteVerificationTag: "XYZabc"



    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: true
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

    # comment
    utteranc:
        enable: true
        repo: aladdinding/utteranc-comments
        issueTerm: title
        theme: github-light


menu:
    main:
        - identifier: Archive
          name: 时间轴
          url: /archives/
          weight: 10
        - identifier: categories
          name: 分类
          url: /categories/
          weight: 20
        - identifier: tags
          name: 标签
          url: /tags/
          weight: 30
        - identifier: search
          name: 搜索
          url: /search/
          weight: 40
        - identifier: about
          name: 关于
          url: /about/
          weight: 50



# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
      anchorLineNos: false
      codeFences: true
      guessSyntax: false
      hl_Lines: ""
      lineAnchors: ""
      lineNoStart: 1
      lineNos: false
      lineNumbersInTable: true
      noClasses: true
      style: dracula
      tabWidth: 4